### ISSUE TITLE
Refactor path template to match other languages

### ISSUE THREAD

**Issue by saicheems** [googleapis/gax-golang#11]
Particularly, use go's yacc to generate the parser.

**Comment by jba** [comment]
I think yacc is overkill. A simple recursive descent parser should be enough. Let me take a crack at it.

**Comment by saicheems** [comment]
Yeah sure, I think it should be relatively easy, as it's a small grammar.
For reference, the parser implementation in Python:
https://github.com/googleapis/gax-python/blob/master/google/gax/path_template.py#L162
