### ISSUE TITLE
Add call options for page size and page token

### ISSUE THREAD

**Issue by jba** [googleapis/gax-golang#15]
Standard Google API List methods usually have page size and page token fields in the request proto to support pagination. If the generated list method (or a hand-wrapped version of it) does not take the actual request proto, the easiest way to specify page size and page token is with options. Since methods that call RPCs already take call options, we should add options for page size and token.

**Comment by saicheems** [comment]
Opting not to resolve this in GAX - will add to the iterator struct in the generated client instead.
